// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DNARepo is an autogenerated mock type for the DNARepo type
type DNARepo struct {
	mock.Mock
}

// GetStats provides a mock function with given fields:
func (_m *DNARepo) GetStats() (int, int, float64) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 float64
	if rf, ok := ret.Get(2).(func() float64); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(float64)
	}

	return r0, r1, r2
}

// Save provides a mock function with given fields: dna, isMutant
func (_m *DNARepo) Save(dna []string, isMutant bool) error {
	ret := _m.Called(dna, isMutant)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, bool) error); ok {
		r0 = rf(dna, isMutant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
