// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "cerebro/domain"

	mock "github.com/stretchr/testify/mock"
)

// MutantVerifier is an autogenerated mock type for the MutantVerifier type
type MutantVerifier struct {
	mock.Mock
}

// GetStats provides a mock function with given fields:
func (_m *MutantVerifier) GetStats() domain.Stats {
	ret := _m.Called()

	var r0 domain.Stats
	if rf, ok := ret.Get(0).(func() domain.Stats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.Stats)
	}

	return r0
}

// IsMutant provides a mock function with given fields: dna
func (_m *MutantVerifier) IsMutant(dna []string) bool {
	ret := _m.Called(dna)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]string) bool); ok {
		r0 = rf(dna)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
